if [ -z $TMUX ]; then
  # Ignore the first ctrl-d
  export IGNOREEOF=1

  # AWS environment
  export AWS_CLI=/usr/local/bin/aws
  export AWS_REGION=ap-southeast-2
  export AWS_USER=kevin.littlejohn
  export STACK_NAME=kevinl

  # Ruby
  export GEM_HOME=/usr/local/ruby/lib/ruby/gems/2.1.0
  export GEM_PATH=/usr/local/ruby/lib/ruby/gems/2.1.0
  /usr/local/ruby/bin/bundle config --global jobs 4

  # SSH agent and keys
  eval $(ssh-agent -s -a /tmp/ssh-agent.sock)
  [ -d ~/.ssh/auto ] && ssh-add ~/.ssh/auto/*

  # git configuration
  git config --global color.ui auto \
    && git config --global user.email "kevin@littlejohn.id.au" \
    && git config --global user.name "Kevin Littlejohn" \
    && git config --global push.default simple \
    && git config --global github.user silarsis
fi

# Tmux belts the PATH because login bash runs /etc/profile
export PATH=$PATH:/usr/local/ruby/bin

# Handy aliases and functions
alias laptop='ssh laptop'
alias say='ssh laptop say'
alias atom='ssh laptop /usr/local/bin/atom $(pwd -P)'
either() { if [[ $? == 0 ]] ; then echo $1 ; else echo $2 ; fi }

[ -f ~/.bashrc ] && . ~/.bashrc

export PS1="\[\033[0;31m\][`cat /usr/local/etc/container_name`]\[\033[0m\]:\u:\w\$ "

reset
