#!/bin/bash

if [ -z "${APTCACHER_PORT_3142_TCP_ADDR}" ]; then
  if $(nc -zw1 ${APTCACHER_PORT_3142_TCP_ADDR}:${APTCACHER_PORT_3142_TCP_PORT}); then
    echo "http://${APTCACHER_PORT_3142_TCP_ADDR}:${APTCACHER_PORT_3142_TCP_PORT}/"
    exit
  fi
fi

GW=$(/sbin/route -n | grep '^0.0.0.0' | awk '{ print $2 }')
nc -zw1 ${GW} 3142 && echo "http://${GW}:3142/" || echo "DIRECT"
